[package]
name = "libertem-dectris"
authors = ["Alexander Clausen <a.clausen@fz-juelich.de>"]
license = "MIT"
version = "0.2.0"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "libertem_dectris"
crate-type = ["cdylib"]

[[bin]]
name = "libertem-dectris"
path = "src/main.rs"

[dependencies]
bincode = "1.3.3"
clap = { version = "3.2.16", features = ["derive"] }
crossbeam = "0.8.2"
crossbeam-channel = "0.5.6"
log = "0.4.17"
memmap2 = "0.5.6"
pyo3 = { version = "0.16.5", features = ["extension-module", "abi3-py37"] }
pyo3-log = "0.6.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
spin_sleep = "1.1.1"
uuid = { version = "1.1.2", features = ["v4", "fast-rng"] }
zmq = { version = "0.9.2", features = ["vendored"] }

[profile.release]
debug = true
